import { Router, Request, Response } from 'express';
import * as userController from '../controllers/userController';
import { authenticateToken } from '../middleware/authMiddleware';
import { UserRole } from '../../types';
const router = Router();
router.post('/register', userController.register);
router.post('/login', userController.login);
router.post('/login/admin', userController.loginAdmin);
router.post('/logout', userController.logout);
router.get('/', authenticateToken, userController.getAllUsers);
router.get('/profile', authenticateToken, userController.getProfile);
router.get('/me/bootcamps', authenticateToken, userController.getAssignedBootcamps);
router.get('/bootcamps', authenticateToken, userController.getAssignedBootcamps);
router.delete('/:id', authenticateToken, userController.deleteUser);
router.patch('/:id/department', authenticateToken, userController.updateUserDepartment);
router.post('/:userId/admin-permission', authenticateToken, userController.grantAdminPermission);
router.delete('/:userId/admin-permission', authenticateToken, userController.revokeAdminPermission);
router.get('/admins', authenticateToken, userController.getAllAdmins);
export default router;
